### ISSUE TITLE
issue with glob patterns not finding files

### ISSUE THREAD

**Issue by danielmklein** [irongut/CodeCoverageSummary#102]
## Bug Report

I have been unable to get this action to work when dealing with files I downloaded from GitHub Actions artifacts that were uploaded in a previous job step. Even though I can use a plain `ls` command to list the files as expected, no `filename` param I've tried works to get this Action to pick up the files. Am I missing or misunderstanding something? Please let me know if there is any more context/detail I can add that will be helpful!

### Workflow File
```yaml
# This gets run in a parallel matrix setup, so we will end up with multiple coverage files uploaded as artifacts
test:
    # Rspec is configured to output to `coverage/coverage.xml` 
    - name: run rspec
       run: bundle exec rspec

    # Upload coverage output as an artifact so we can download them all later
    - name: Upload Coverage Output
      uses: actions/upload-artifact@v2
      with:
          name: coverage-output-rspec-${{ matrix.ci_node_index }}.coverage.xml
          path: coverage/coverage.xml

# Now lets download the coverage file artifacts and use them!
do_coverage_stuff:
  needs: test
  runs-on: ubuntu-latest
  steps:
      - name: Download Coverage Outputs
        uses: actions/download-artifact@v3
        with:
            path: artifacts

      # this shows that I have...
      # coverage-output-rspec-0.coverage.xml
      # coverage-output-rspec-1.coverage.xml
      # ...
      # coverage-output-rspec-N.coverage.xml
      - name: list artifacts
        run: ls artifacts

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
            # I have tried...
            # artifacts/*.xml
            # artifacts/*.coverage.xml
            # **/*.xml
            #
            # to no avail
            # I've also tried downloading the artifacts to the working directory instead of `./artifacts`
            filename: artifacts/coverage-output-rspec-0.coverage.xml
            badge: true
            fail_below_min: false
            format: markdown
            hide_branch_rate: false
            hide_complexity: true
            indicators: true
            output: both
            thresholds: '50 60'
```

### Actions Log
```
Run ls
  ls
  shell: /usr/bin/bash -e {0}
coverage-output-rspec-0.coverage.xml
coverage-output-rspec-1.coverage.xml
coverage-output-rspec-10.coverage.xml
coverage-output-rspec-11.coverage.xml
coverage-output-rspec-12.coverage.xml
coverage-output-rspec-13.coverage.xml
coverage-output-rspec-14.coverage.xml
coverage-output-rspec-2.coverage.xml
coverage-output-rspec-3.coverage.xml
coverage-output-rspec-4.coverage.xml

... snip ...

Run irongut/CodeCoverageSummary@v1.3.0
  
... snip ...

Error: No files found matching glob pattern.
```

### Expected Behavior
`CodeCoverageSummary` should be able to find and process the files in the working directory.
