### ISSUE TITLE
Duplicate references with different code coverage results

### ISSUE THREAD

**Issue by leahy268** [irongut/CodeCoverageSummary#117]
## Bug Report

I love the short code coverage report with every little bit of information that we need.  

However when I get the results they make no sense.  I seem to have the same namespace listed more than once and have different coverage results.  It's as though it isn't combining the multiple coverage reports properly.

### Workflow File
```yaml
- name: ReportGenerator
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: src/**/TestResults/*/coverage.cobertura.xml
          badge: true
          format: markdown
          indicators: true
          output: both
```

### Actions Log
```
I couldn't easily seperate this - private repo.

```

### Expected Behavior
I would expect to see just 1 line for each namespace and 1 line for each class
Currently I get this list repeated several times. 

![image](https://user-images.githubusercontent.com/58454534/206065841-b863308c-b92c-44fd-b47d-7f54fa510192.png)
Figure: Amazon.Client listed at least 3 times (Blurred for privacy)

### Linked To
List any issues linked to this bug.

**Comment by LMSSonos** [comment]
@leahy268 - I had the same issue. Reason for the duplicates was that I had like 2 unittest projects, they referenced a shared library which was used in both test-projects. so It generated multiple coverage.cobertura.xml files. 

I use `dotnet-coverage` (https://learn.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-coverage) and merge the results before I create the report, see here the actions


```      
      - name: Merge coverage reports
        run: |
          dotnet tool install --global dotnet-coverage
          cd testresults
          dotnet-coverage merge -o coverage-merged.xml -f cobertura -r coverage.cobertura.xml

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./testresults/coverage-merged.xml
          format: markdown
          output: both
```
