### ISSUE TITLE
Add summary to a PR

### ISSUE THREAD

**Issue by irongut** [irongut/CodeCoverageSummary#13]
## Feature Request

Add the code coverage summary to a pull request without needing another Action. This could be optional.

Using Octokit this should be straightforward, if run from a PR the id of the PR can be obtained from the runner environment. An optional id parameter could allow posting to a PR when not run from a PR (e.g. manual run).

### Expected Behaviour

Posts the coverage summary to a PR in a similar way to the marocchino/sticky-pull-request-comment action.

**Comment by fredrikaverpil** [comment]
You can use a third-party action for that, like so:

```yaml
  steps:
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        format: "markdown"
        output: "both"

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
```
