### ISSUE TITLE
System.OutOfMemoryException when generating a coverage summary

### ISSUE THREAD

**Issue by maddiemort** [irongut/CodeCoverageSummary#133]
## Bug Report

I'm trying to generate a coverage summary from a coverage report in cobertura format, produced using [`grcov`](https://github.com/mozilla/grcov), and this action fails with the error message "Parsing Error: Exception of type 'System.OutOfMemoryException' was thrown."

### Workflow File
```yaml
name: Coverage Report

# ...

env:
  RUSTFLAGS: -Dwarnings -Cinstrument-coverage
  # ...

jobs:
  coverage-report:
    runs-on: ubuntu-latest-32-cores
    steps:
      - name: Clone
        uses: actions/checkout@v2
      # ...
      - name: Install grcov
        run: cargo install grcov
      # ...
      - name: Gather Coverage Data
        run: cargo test
      - name: Generate Coverage Report
        run: grcov . -s . --binary-path ./target/debug/ -t cobertura --branch --ignore-not-existing -o ./target/debug/coverage.cobertura.xml
      - name: Produce Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: target/debug/coverage.cobertura.xml
          badge: true
          format: 'markdown'
          output: 'both'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

```

### Actions Log

From the "Produce Coverage Summary" step:

```
Coverage File: /github/workspace/target/debug/coverage.cobertura.xml
Parsing Error: Exception of type 'System.OutOfMemoryException' was thrown. - /github/workspace/target/debug/coverage.cobertura.xml
##[debug]Docker Action run completed with exit code 254
```

### Expected Behavior

I expected the Action to generate a coverage summary without running out of memory.

### Additional Context

The coverage report is for a large Rust project (~300k LoC).

### Linked To

None.
