### ISSUE TITLE
Jest: Output File and Both Not Generating Markdown File

### ISSUE THREAD

**Issue by bwathen** [irongut/CodeCoverageSummary#140]
## Bug Report

After I generate Jest coverage reports using the Cobertura reporter, this action is failing is failing to generate the markdown-formatted file `code-coverage-results.md`.

I was able to get the console output in the action logs while using `output: both`, but the markdown file `code-coverage-results.md` is never created when using either `output: both` or `output: file`.

The Jest project is nested under `projectRoot/ui/`

### Test Coverage Command in `package.json`
`"test:coverage": "jest src/ --coverage",`

### Coverage Reporter Config in Jest Config File
```javascript
  // Indicates whether the coverage information should be collected while executing the test
  collectCoverage: false, // Overwritten by the pipeline

  // An array of glob patterns indicating a set of files for which coverage information should be collected
  collectCoverageFrom: [
    "src/**/*.ts",
    "!src/**/*.d.ts",
  ],

  // The directory where Jest should output its coverage files
  coverageDirectory: "coverage",

  // An array of regexp pattern strings used to skip coverage collection
  coveragePathIgnorePatterns: [
    "/node_modules/",
  ],

  // Indicates which provider should be used to instrument code for coverage
  // coverageProvider: "babel",

  // A list of reporter names that Jest uses when writing coverage reports
  coverageReporters: [
    // "json",
    "text",
    "lcov",
    // "clover",
    "cobertura",
  ],
```

### Workflow File
```yaml
  unit-test-ui:
    name: Run UI Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node Modules
        uses: ./.github/actions/install-node-modules
      - name: Build Application
        run: npm run build
      - name: Run Unit Tests
        run: npm run test:coverage
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: Coverage Reports
          path: ./ui/coverage/lcov-report
      - name: Generate Markdown Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./ui/coverage/cobertura-coverage.xml
          # badge: true
          # fail_below_min: true
          format: markdown
          # hide_branch_rate: false
          # hide_complexity: true
          indicators: true
          output: file
          thresholds: '70 85'
      - run: ls -la coverage
      - name: Send Coverage Markdown to Job Summary
        run: cat ./ui/coverage/code-coverage-results.md >> $GITHUB_STEP_SUMMARY
```

#### File-only Output
<img width="1628" alt="image" src="https://user-images.githubusercontent.com/15258023/221373396-e8275be1-42d9-46ff-b180-7feaf43d03b0.png">

### Expected Behavior
I expect the `code-coverage-results.md` file to be generated in the `coverage/` folder when given a valid `cobertura-coverage.xml` file.

### Additional Context
I checked the root of the project to see if the markdown file was generated there by accident somehow, but it was not.

### Linked To
N/A
