### ISSUE TITLE
Make Github action to work in pipelines using Windows images

### ISSUE THREAD

**Issue by Catalin-Andronie** [irongut/CodeCoverageSummary#151]
## Feature Request

I want to be able to use this Github action in pipelines that uses Windows images.

### Expected Behaviour

I expect the action to work as intended. At the moment in Windows-based image pipelines, the next error is shown: "Container action is only supported on Linux".

![image](https://user-images.githubusercontent.com/10738038/227772615-089febc3-9067-43bb-99fb-b67bdec4e39d.png)

### Additional Context

Github pipeline example:

```yml
jobs:
  build:
    runs-on: windows-latest
    steps:
    ...
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
```
### Linked To
List any issues linked to this feature request.
