### ISSUE TITLE
How to get coverage per file

### ISSUE THREAD

**Issue by michelkok** [irongut/CodeCoverageSummary#236]
Please, can you help me find how I can get more detailed information in the report? 
<img width="294" alt="image" src="https://github.com/irongut/CodeCoverageSummary/assets/25588435/d710684a-0520-455e-b839-04fda9b12f5b">

I use Coverage.py to generate the `coverage.cobertura.xml` file which does actually contain the information per file in the directory not just the overall score.
<img width="1220" alt="image" src="https://github.com/irongut/CodeCoverageSummary/assets/25588435/e36759a7-b199-4ca6-8fe9-faeb3b5a80ee">

This is part of my Github Actions setup:
```
      - name: Test docker
        run: |
          docker run \
          --rm --volumes-from github_runner \
          ${{ env.TEST_TAG }} \
          /bin/bash -c \
          "python -m coverage run --data-file=/cov/.coverage --branch -m pytest; python -m coverage xml --data-file=/cov/.coverage -o ${RUNNER_WORKDIR}/cov/coverage.cobertura.xml"

      - name: Copy files to workdir
        run: |
          cp ${RUNNER_WORKDIR}/cov/coverage.cobertura.xml ${GITHUB_WORKSPACE}/coverage.cobertura.xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
``` 

Maybe I'm just missing something simple but it seems the docs are not really stating how to do this and from the issues it seems people are able to get them, so how would I have to change my setup?
