### ISSUE TITLE
code coverage 0% and don't know how can i debug

### ISSUE THREAD

**Issue by kunlinyu** [irongut/CodeCoverageSummary#24]
## Bug Report

Provide a short description of the bug with any error message.

### Workflow File
```yaml
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build -j8 --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./bin/unit_tests --gtest_output=xml:${{github.workspace}}/build/report/

    - name: Install gcovr
      run: sudo apt-get install -y gcovr

    - name: Generate cubertura xml by gcovr
      run: gcovr --xml coverage.cobertura.xml --xml-pretty

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.1.0
      with:
        filename: coverage.cobertura.xml
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

```

### Actions Log
```
Run gcovr --xml coverage.cobertura.xml --xml-pretty
  gcovr --xml coverage.cobertura.xml --xml-pretty
  shell: /usr/bin/bash -e {0}
  env:
    BUILD_TYPE: Release
1s
Run irongut/CodeCoverageSummary@v1.1.0
  with:
    filename: coverage.cobertura.xml
    badge: true
    format: markdown
    output: both
    fail_below_min: false
    indicators: true
    thresholds: 50 75
  env:
    BUILD_TYPE: Release
/usr/bin/docker run --name ghcrioirongutcodecoveragesummaryv110_7058e7 --label e28490 --workdir /github/workspace --rm -e BUILD_TYPE -e INPUT_FILENAME -e INPUT_BADGE -e INPUT_FORMAT -e INPUT_OUTPUT -e INPUT_FAIL_BELOW_MIN -e INPUT_INDICATORS -e INPUT_THRESHOLDS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/geomcpp/geomcpp":"/github/workspace" ghcr.io/irongut/codecoveragesummary:v1.1.0  "coverage.cobertura.xml" "--badge" "true" "--fail" "false" "--format" "markdown" "--indicators" "true" "--output" "both" "--thresholds" "50 75"
Code Coverage File: coverage.cobertura.xml
![Code Coverage](https://img.shields.io/badge/Code%20Coverage-0%25-critical?style=flat)

Package | Line Rate | Branch Rate | Complexity | Health
-------- | --------- | ----------- | ---------- | ------
**Summary** | **0%** (0 / 0) | **0%** (0 / 0) | 0 | ❌

1s
Run marocchino/sticky-pull-request-comment@v2
  with:
    recreate: true
    path: code-coverage-results.md
    append: false
    delete: false
    hide_details: false
    hide: false
    hide_and_recreate: false
    hide_classify: OUTDATED
    GITHUB_TOKEN: ***
  env:
    BUILD_TYPE: Release
```

### Expected Behavior
show the correct coverage report

### Additional Context
I try the commond
``gcovr --xml coverage.cobertura.xml --xml-pretty
in the root directory of my local environmen.
the file "coverage.cobertura.xml" creates success.
I don't know how can i debug.
