### ISSUE TITLE
xml bug plus feature xover

### ISSUE THREAD

**Issue by sarnold** [irongut/CodeCoverageSummary#28]
## Bug Report

Summary report is created, but branch rate is zero ("0").  Line rate looks okay.

### Workflow File

see the logs and coverage workflow on [this PR](https://github.com/VCTLabs/redis-ipc/pull/28)

### Feature Bits

This is trying to process the output (of my cleaned up fork) of [lcov-to-cobertura-xml](https://github.com/sarnold/lcov-to-cobertura-xml)

Wrinkle 2 is that ^^ is the only convenient tool to process clang source-based coverage output => llvm-cov => lcov.info (tracefile format) then lcov_cobertura => xml format

[coverage.xml.txt](https://github.com/irongut/CodeCoverageSummary/files/7558982/coverage.xml.txt)

**Comment by irongut** [comment]
@sarnold  I've an idea what the problem might be and should get time to fix it over the weekend.

**Comment by irongut** [comment]
@sarnold I've tested your coverage.xml file every way I could think of locally and on GitHub using a test repo. Using v1.0.5, v1.1.0 or my local development version I get the correct results every time:

> Code Coverage File: coverage.xml
> Package | Line Rate | Branch Rate | Complexity | Health
> -------- | --------- | ----------- | ---------- | ------
> inc | 38% | 55% | 0 | ❌
> src | 65% | 41% | 0 | ➖
> **Summary** | **61%** (557 / 913) | **42%** (117 / 280) | 0 | ➖

The metrics in your coverage.xml file are in a different order to my samples which I thought might be a problem but my code doesn't rely on the order and I can't replicate the problem. So, I'm confused why it's not working for you.

I had a look at the [coverage.yml](https://github.com/VCTLabs/redis-ipc/blob/36bffbc5a96027c7fb9b158d5a0e788534c186b2/.github/workflows/coverage.yml) workflow and noticed you run the CCS action twice.

```yaml
    - name: Code Coverage Summary Report (data)
      uses: irongut/CodeCoverageSummary@v1.1.0
      with:
        filename: coverage.xml
        output: 'both'

    - name: Check code coverage
      id: coverage
      env:
        VALUE: "Branch Rate"
      run: |
        COVERAGE="$( cat code-coverage-results.txt | egrep "^${VALUE}" | sed -e 's#^.* \([0-9]*\)%.*#\1#' )"
        echo "##[set-output name=coverage;]${COVERAGE}"
        echo "##[set-output name=coverage-rounded-display;]${COVERAGE}%"

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.1.0
      if: ${{ github.event_name == 'pull_request' }}
      with:
        filename: coverage.xml
        format: 'markdown'
        output: 'both'
```

Looking at the run when you updated to v1.1.0 [here](https://github.com/VCTLabs/redis-ipc/runs/4246629572?check_suite_focus=true) the step between fails so CCS only runs once. I've not used a Unix/Linux shell much since 20 years ago and I have to admit I don't understand what that step is doing.
