### ISSUE TITLE
Discrepancies in code coverage between irongut/CodeCoverageSummary and PublishCodeCoverageResults@1

### ISSUE THREAD

**Issue by paweljankowskicolumbus** [irongut/CodeCoverageSummary#304]
## Bug Report

Code coverage seems to be 0% for some of the projects, while there is coverage almost 100%.

### Workflow File
```yaml
      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage/**/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'
```

### Expected Behavior
Code coverage summary should not differ depend on CI/CD environment

### Additional Context
You can see results on attached screenshots below, Azure Devops shows correct values while CodeCoverageSummary action zeroes it for one project. Also, how branch rate can be 100% while line rate is 0%

![ironGut](https://github.com/irongut/CodeCoverageSummary/assets/153195536/9bf947e4-6e6a-426a-8a58-668307f6a961)
![azureDevops](https://github.com/irongut/CodeCoverageSummary/assets/153195536/82bde107-9e72-4d34-9581-923bf0490e14)
