### ISSUE TITLE
Parsing Error: Coverage fill invalid, data not found. target/site/jacoco/jacoco.xml

### ISSUE THREAD

**Issue by briceashburn** [irongut/CodeCoverageSummary#341]
## Bug Report

Java Spring Boot application. xml file seems to be improperly formatted and may be the cause.

### Workflow File
```yaml
   steps:
      - uses: actions/setup-java@v4.2.2
        with:
          distribution: 'oracle'
          java-version: '17'
          overwrite-settings: false
 
      - uses: actions/checkout@v4.1.7
      - name: Build with Maven
        run: mvn -B clean verify
 
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: './target/site/jacoco/jacoco.xml'
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
```

### Actions Log
```
Parsing Error: Coverage fill invalid, data not found. target/site/jacoco/jacoco.xml
```

### Expected Behavior
Expected behavior should be a formatted XML and successfully report.

### Linked To
List any issues linked to this bug.
