### ISSUE TITLE
SimpleCov solution

### ISSUE THREAD

**Issue by edgarv09** [irongut/CodeCoverageSummary#45]
## Feature Request

I already face the problem of using simple coverage and this action but i found a complete solution

### Expected Behaviour
Update the wiki.

As you mentioned in the description, this action is waiting for a Cobertura file, so why not tell simplecov to generate a Cobertura file?
I found this gem https://github.com/dashingrocket/simplecov-cobertura 
just follow the instructions to setup and it's done.

example of config into `spec_helper.rb`
```ruby
require 'simplecov-cobertura'
SimpleCov.formatters = SimpleCov::Formatter::MultiFormatter.new([
  SimpleCov::Formatter::SimpleFormatter,
  SimpleCov::Formatter::CoberturaFormatter,
  SimpleCov::Formatter::HTMLFormatter
])
``` 
above config would generate HTML, and cobertura files. 

example of action config 

```yaml
     # Add or replace test runners here
      - name: Build and test with rspec
        run: |
          COVERAGE=true bundle exec rspec spec

      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: ./coverage/coverage.xml
          badge: true
          hide_branch_rate: true
          hide_complexity: true
          format: markdown
          indicators: true
          output: both
```

<img width="442" alt="image" src="https://user-images.githubusercontent.com/11460639/174928563-f9f99903-4f20-4eac-b320-b86396ae9aa1.png">
