### ISSUE TITLE
Running on ARM64 fails

### ISSUE THREAD

**Issue by protoblade** [irongut/CodeCoverageSummary#60]
## Bug Report
when migrating from x86_64 to arm64 (aws graviton) the build started to get the following error

### Workflow File
```yaml
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '0 80'
```

### Actions Log
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

### Expected Behavior
Runs on arm as on x86

### Additional Context
no

### Linked To
none
