### ISSUE TITLE
Not working with JEST 

### ISSUE THREAD

**Issue by karthik2265** [irongut/CodeCoverageSummary#76]
I am using JEST for testing and I am generating the coverage report in cobertura format, and this error shows up when the workflow is run.

```js
Coverage File: /github/workspace/coverage/cobertura-coverage.xml
Parsing Error: No package data found - /github/workspace/coverage/cobertura-coverage.xml
```

yml workflow file:

```yml
name: Node tests (with coverage)
on:
  push:
    branches:
      - '*'
      - '!master'
      - '!SS-test'
      - '!SS-UAT-test'
      - '!PS-prod'
  pull_request:
    branches:
      - 'master'
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install npm packages
        run: npm ci
      
      - name: Test 
        run: npm run test:coverage

      - name:
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: "coverage/" # or path/to/artifact

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "/coverage/cobertura-coverage.xml"
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
```

could someone please help me figure out whats going wrong
